name: Docker CI

on:
  push:
    branches:
    - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Build and push the Angular Docker image
      run: |
        echo "${{ secrets.TOKEN_PWD }}" | docker login -u devs2blu-avengers --password-stdin ghcr.io
        docker build -t ghcr.io/devs2blu-avengers/savebludashboard:latest .
        docker push ghcr.io/devs2blu-avengers/savebludashboard:latest

    - name: Deploy to AWS EC2
      run: |
        echo "${{ secrets.AWS_SSH_KEY }}" > /tmp/deploy_rsa
        chmod 600 /tmp/deploy_rsa
        ssh -o StrictHostKeyChecking=no -i /tmp/deploy_rsa ubuntu@52.23.70.87 << EOF
        
        cd /home/ubuntu
        echo "${{ secrets.TOKEN_PWD }}" | sudo docker login -u devs2blu-avengers --password-stdin ghcr.io
        # Stop containers that might be using port 80 (as Nginx will be serving on port 80)
        CONTAINER_ID=\$(sudo docker ps -q --filter "publish=80")
        if [ ! -z "\$CONTAINER_ID" ]; then
          sudo docker stop \$CONTAINER_ID
          sudo docker rm \$CONTAINER_ID
        fi
        
        sudo docker pull ghcr.io/devs2blu-avengers/savebludashboard:latest
        sudo docker run -d -p 80:80 ghcr.io/devs2blu-avengers/savebludashboard:latest
        EOF
